# Generated by Django 5.0.2 on 2024-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='cautions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='directions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='eco_friendly',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='faqs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='handcrafted_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='key_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='key_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='marketed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='packed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='quality_assurance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='safety_warnings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='weight',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
