# Generated by Django 5.0.2 on 2024-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productitem_benefits_productitem_cautions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='expiry',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
