# Generated by Django 5.0.2 on 2024-02-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='direction_to_use',
            new_name='who_can_use',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='handcrafted_by',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='marketed_by',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='packed_by',
        ),
    ]
