# Generated by Django 5.0.2 on 2024-02-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_direction_to_use_productitem_who_can_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='url_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='category',
            field=models.CharField(choices=[('fragrances', 'Fragrances'), ('body_bath', 'Body Bath'), ('skin', 'Skin'), ('candles', 'Candles')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='sub_category',
            field=models.CharField(choices=[('fragrances', [('dhuni', 'Dhuni'), ('perfumes', 'Perfumes'), ('attars', 'Attars')]), ('body_bath', [('soaps', 'Soaps'), ('shower_gel', 'Shower Gel'), ('facewash', 'Face Wash'), ('shampoo', 'Shampoo'), ('conditioner', 'Conditioner'), ('lotion', 'Lotion')]), ('skin', [('facetoner', 'Face Toner'), ('aleo_gel', 'Aleo Gel'), ('lip care', 'Lip Care'), ('body_hair oil', 'Body Hair Oil'), ('serum', 'Serum')]), ('candles', [('candle', 'Candle')])], max_length=20),
        ),
    ]
